version: '3.8'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: docker/telegram_bot/Dockerfile.local
    container_name: telegram_bot
    env_file:
      - .env
    ports:
      - "${TELEGRAM_PORT}:${TELEGRAM_PORT}"
    volumes:
      - .:/telegram_bot
    depends_on:
      - mongo

  http_server:
    build:
      context: .
      dockerfile: docker/http_server/Dockerfile.local
    container_name: http_server
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - .:/http_server
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
