services:
  bot:
    build:
      context: ./bot
      dockerfile: ./docker/Dockerfile.local
    container_name: ${PROJECT_NAME}_bot
    env_file:
      - .env
    volumes:
      - ./bot:/bot
    networks:
      - main
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: ${PROJECT_NAME}_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    command: mongod --port ${MONGO_PORT}
    volumes:
      - mongo:/data/db
    networks:
      - main

volumes:
  mongo:
  bot:


networks:
  main:
