version: '3.8'

services:
  ten_tarot_bot:
    build:
      context: .
      dockerfile: docker/telegram_bot/Dockerfile.local
    container_name: ten_tarot_bot
    env_file:
      - .env
    ports:
      - "${TELEGRAM_PORT}:${TELEGRAM_PORT}"
    volumes:
      - .:/telegram_bot
    depends_on:
      - ten_tarot_db

  ten_tarot_server:
    build:
      context: .
      dockerfile: docker/http_server/Dockerfile.local
    container_name: ten_tarot_server
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - .:/http_server
    depends_on:
      - ten_tarot_db

  ten_tarot_db:
    image: mongo:latest
    container_name: ten_tarot_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    command: mongod --port ${MONGO_PORT}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
