FROM golang:1.22

WORKDIR /http_server

COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY ./cmd/http_server ./cmd/http_server
COPY ./config ./config
COPY ./internal ./internal
COPY ./docs ./docs
COPY ./pkg ./pkg

CMD ["go", "run", "./cmd/http_server"]
