FROM golang:1.22-alpine AS builder

WORKDIR /telegram_bot

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd/telegram_bot ./cmd/telegram_bot
COPY ./config ./config
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN go build -o /app/telegram_bot ./cmd/telegram_bot/main.go

FROM alpine:latest

COPY --from=builder /app/telegram_bot /app/telegram_bot

CMD ["/app/telegram_bot"]
