FROM golang:1.22

WORKDIR /telegram_bot

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd/telegram_bot ./cmd/telegram_bot
COPY ./config ./config
COPY ./internal ./internal

CMD ["sh", "-c", "while :; do sleep 1; done"]
