FROM golang:1.22-alpine AS builder

WORKDIR /bot

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

RUN go build -o /app/bot ./cmd/app

FROM alpine:latest

COPY --from=builder /app/bot /app/bot

RUN adduser -D -g '' appuser
RUN chown appuser /app/bot
USER appuser

CMD ["/app/bot"]