basePath: /api/v1
definitions:
  entity.Pagination:
    properties:
      countPerPage:
        type: integer
      currentPage:
        type: integer
      total:
        type: integer
    type: object
  entity.TGMessage:
    properties:
      answer:
        type: string
      chat_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      text:
        type: string
    type: object
  entity.TGUser:
    properties:
      chat_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  response.pagination:
    properties:
      data: {}
      pagination:
        $ref: '#/definitions/entity.Pagination'
    type: object
info:
  contact: {}
  title: Ten tarot tg bot api
  version: "1.0"
paths:
  /tg-messages:
    get:
      consumes:
      - application/json
      description: Show all messages list
      parameters:
      - description: ChatID
        in: query
        name: chat_id
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Count
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.pagination'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.TGMessage'
                  type: array
              type: object
      summary: Show messages
      tags:
      - tg-messages
  /tg-users:
    get:
      consumes:
      - application/json
      description: Show users list
      parameters:
      - description: Username
        in: query
        name: username
        type: string
      - description: ChatID
        in: query
        name: chat_id
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Count
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.pagination'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.TGUser'
                  type: array
              type: object
      summary: Show users
      tags:
      - tg-users
swagger: "2.0"
